### ISSUE TITLE
Make modal dialog with samples table wider

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#495]
Initially suggested on https://github.com/AlexsLemonade/refinebio-frontend/pull/486#issuecomment-452839056 by @Miserlou 

> Any chance we can make the modal responsive?
> 
> Weird that I have to use non standard scroll buttons to scroll a narrow window on an ultrawide monitor
> ![screen shot 2019-01-09 at 3 06 18 pm](https://user-images.githubusercontent.com/139987/50925413-41629700-1420-11e9-812c-c095d0acac63.png)

Tagging @dvenprasad for discussion

**Comment by dvenprasad** [comment]
I experimented with the font size, padding to figure out how the content in it can look less bad. 
- Change table font to 14px
- Reduce add button padding to 2px x 24px

<img width="1171" alt="screen shot 2019-01-31 at 3 47 54 pm" src="https://user-images.githubusercontent.com/15315514/52084388-fe539980-256f-11e9-87b0-9d7eacd8977f.png">


- Another item @arielsvn and I discussed was to set max width of the modal relative to the number of columns to make sure stuff like this doesn't happen (which hurts readability) 

![screen shot 2019-01-31 at 3 01 09 pm](https://user-images.githubusercontent.com/15315514/52083967-f1827600-256e-11e9-82ef-8fbc9fa4fddf.png)


- 5 columns - 1100px (this is pretty much the least number of columns an experiment can have)
- 6 columns - 1300px
-7 columns - 1500px
- 8+ columns - 1900px (based on how many metadata fields are normalized, this is designed to handle a max of 10-12 columns depending on contents of the columns while still maintaining readability)

I want to note that the title column will feel a more snug than others. This has more to do with how the width of each column is set. I'm not sure if we have control over that. 

- Add on hover color on each row, so users are able to follow which row they are looking at on wider screens.

**Comment by dvenprasad** [comment]
hover color: #e2e2e2

**Comment by arielsvn** [comment]
We'll add a [shake animation] for the horizontal scroll buttons when they are displayed.

```css
@keyframes eva-shake {
  from,
  to {
    transform: translate3d(0, 0, 0); }
  10%,
  30%,
  50%,
  70%,
  90% {
    transform: translate3d(-3px, 0, 0); }
  20%,
  40%,
  60%,
  80% {
    transform: translate3d(3px, 0, 0); } }
```
